### ISSUE TITLE
Please fix your readme

### ISSUE THREAD

**Issue by kbyyd24** [spring-cloud-samples/stub-runner-boot#1]
The property `stubrunner.ids` example in readme is :  `groupId:artifactId:classifer:version:port`.
But it should be `groupId:artifactId:version:classifer:port`.
Please fix it.

**Comment by marcingrzejszczak** [comment]
Care to file a PR?

**Comment by kbyyd24** [comment]
Hi @marcingrzejszczak , I'm sorry I missed this message 😂 .
I found this issue is still there, I'll file a PR for this.

**Comment by kbyyd24** [comment]
Hi @marcingrzejszczak , I created a PR to fix this. Could you review & merge it?

**Comment by marcingrzejszczak** [comment]
Yup! It's merged
